apiVersion: v1
kind: Service
metadata:
  name: cicddockerimageinkubernetes
spec:
  type: LoadBalancer
  ports:
    - port: 2323
      targetPort: 80
  selector:
    app: kuberneticsdemo-pod
